@baseUrl=http://localhost:1006/v1/2024

POST {{baseUrl}}/user/register
Content-Type: application/json

{
    "verify_key": "Vinhtiensinh17@gmail.com",
    "verify_purpose": "TEST_USER",
    "verify_type": 1
}


GET http://localhost:8008/v1/2024/checkStatus