// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AcceptOrderCompletion(ctx context.Context, id uuid.UUID) error
	AddPermissionToRole(ctx context.Context, arg AddPermissionToRoleParams) error
	AddRoleToUser(ctx context.Context, arg AddRoleToUserParams) error
	CheckOTPVerifyExist(ctx context.Context, verifyKey string) (bool, error)
	CheckRefreshToken(ctx context.Context, refreshToken string) (uuid.UUID, error)
	CheckUserExist(ctx context.Context, email string) (bool, error)
	CreateDispute(ctx context.Context, arg CreateDisputeParams) (Dispute, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	CreateRole(ctx context.Context, name string) (Role, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Gig, error)
	CreateUserBase(ctx context.Context, arg CreateUserBaseParams) (uuid.UUID, error)
	CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) error
	DeleteService(ctx context.Context, id uuid.UUID) error
	DeleteUserBase(ctx context.Context, userBaseID uuid.UUID) error
	GetChatHistory(ctx context.Context, arg GetChatHistoryParams) ([]Message, error)
	GetDisputeByID(ctx context.Context, id uuid.UUID) (Dispute, error)
	GetDisputeByOrderID(ctx context.Context, orderID uuid.UUID) (Dispute, error)
	GetInfoOTP(ctx context.Context, verifyHashKey string) (GetInfoOTPRow, error)
	GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error)
	GetPermissionsByRoleID(ctx context.Context, roleID int32) ([]Permission, error)
	GetPermissionsByUserID(ctx context.Context, userID uuid.UUID) ([]Permission, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetRolesByUserID(ctx context.Context, userID uuid.UUID) ([]Role, error)
	GetRoomChatByUserId(ctx context.Context, user1ID uuid.UUID) ([]GetRoomChatByUserIdRow, error)
	GetRoomInfo(ctx context.Context, id uuid.UUID) (GetRoomInfoRow, error)
	GetService(ctx context.Context, id uuid.UUID) (GetServiceRow, error)
	GetUserBaseToCheckLogin(ctx context.Context, email string) (GetUserBaseToCheckLoginRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserInfoToSetToken(ctx context.Context, userBaseID uuid.UUID) (GetUserInfoToSetTokenRow, error)
	InsertOTPVerify(ctx context.Context, arg InsertOTPVerifyParams) (uuid.UUID, error)
	ListDisputes(ctx context.Context) ([]Dispute, error)
	ListOrdersByUser(ctx context.Context, buyerID uuid.UUID) ([]Order, error)
	ListUsersByType(ctx context.Context, userType string) ([]User, error)
	RemovePermissionFromRole(ctx context.Context, arg RemovePermissionFromRoleParams) error
	RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error
	SetChatHistory(ctx context.Context, arg SetChatHistoryParams) (Message, error)
	SubmitOrderDelivery(ctx context.Context, id uuid.UUID) error
	UpdateDisputeStatus(ctx context.Context, arg UpdateDisputeStatusParams) error
	UpdateLoginInfo(ctx context.Context, arg UpdateLoginInfoParams) error
	UpdateLogoutInfo(ctx context.Context, userBaseID uuid.UUID) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	UpdateService(ctx context.Context, arg UpdateServiceParams) (Gig, error)
	UpdateUserBaseToken(ctx context.Context, arg UpdateUserBaseTokenParams) error
	UpdateUserVerificationStatus(ctx context.Context, verifyHashKey string) error
}

var _ Querier = (*Queries)(nil)
