server:
  port: 8080
  mode: "dev"
postgresql:
  host: postgres
  port: 5432
  username: postgres
  password: 123456
  dbname: test
kafka:
  brokers: kafka:29092
redis:
  host: localhost
  port: 6379
  password:
  database: 0
elasticsearch:
  host: elasticsearch
  port: 9200
