// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Answer struct {
	ID         uuid.UUID
	OrderID    uuid.UUID
	UserID     uuid.UUID
	QuestionID uuid.UUID
	Answer     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Category struct {
	ID        int32
	Name      string
	ParentID  sql.NullInt32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Dispute struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	UserID    uuid.UUID
	Reason    string
	Status    string
	CreatedAt time.Time
}

type Gig struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Title       string
	CategoryID  []int32
	ImageUrl    []string
	Description string
	PricingMode string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type GigPackage struct {
	ID           uuid.UUID
	GigID        uuid.UUID
	Tier         string
	Price        float64
	DeliveryTime int32
	Options      pqtype.NullRawMessage
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type GigRequirement struct {
	ID        uuid.UUID
	GigID     uuid.UUID
	Question  string
	Required  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type LedgerEntry struct {
	ID            uuid.UUID
	WalletID      uuid.NullUUID
	TransactionID uuid.NullUUID
	AmountBigint  int64
	BalanceAfter  int64
	EntryType     string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Message struct {
	ID         uuid.UUID
	RoomID     uuid.UUID
	SenderID   uuid.UUID
	ReceiverID uuid.UUID
	Content    string
	SentAt     time.Time
}

type MessageAttachment struct {
	ID         uuid.UUID
	MessageID  uuid.UUID
	FileUrl    string
	FileType   sql.NullString
	FileName   sql.NullString
	UploadedAt sql.NullTime
	CreatedAt  sql.NullTime
}

type Order struct {
	ID             uuid.UUID
	GigID          uuid.UUID
	BuyerID        uuid.UUID
	SellerID       uuid.UUID
	Status         string
	TotalPrice     float64
	OrderDate      time.Time
	DeliveryDate   sql.NullTime
	IdempotencyKey string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type PaymentTransaction struct {
	ID            uuid.UUID
	TopupOrderID  uuid.NullUUID
	Provider      string
	ProviderTxID  string
	AmountBigint  int64
	Status        string
	RemotePayload pqtype.NullRawMessage
	Signature     sql.NullString
	VerifiedAt    sql.NullTime
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Permission struct {
	ID        uuid.UUID
	Name      string
	Resource  string
	Action    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Review struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	Reviewer  uuid.UUID
	Rating    int32
	Comment   sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Role struct {
	ID        uuid.UUID
	RoleName  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type RolePermission struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Room struct {
	ID        uuid.UUID
	User1ID   uuid.UUID
	User2ID   uuid.UUID
	CreatedAt time.Time
}

type TopupOrder struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	OrderID            uuid.NullUUID
	ReferenceCode      string
	IdempotencyKey     string
	AmountBigint       int64
	Currency           string
	Provider           string
	ProviderPaymentUrl sql.NullString
	Status             string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	ExpiresAt          sql.NullTime
}

type User struct {
	ID         uuid.UUID
	UserBaseID uuid.UUID
	Names      string
	ProfilePic sql.NullString
	Bio        sql.NullString
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type UserBase struct {
	UserBaseID         uuid.UUID
	Email              string
	Salt               string
	Passwords          string
	IsTwoFactorEnabled int16
	LoginTime          sql.NullTime
	LogoutTime         sql.NullTime
	LoginIp            string
	States             int16
	RefreshToken       string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type UserRole struct {
	UserID    uuid.UUID
	RoleID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserVerify struct {
	ID            uuid.UUID
	VerifyKey     string
	VerifyHashKey string
	VerifyOtp     string
	VerifyType    string
	IsDeleted     bool
	IsVerified    bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type ViewPendingTopup struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	ReferenceCode string
	AmountBigint  int64
	Currency      string
	Provider      string
	Status        string
	CreatedAt     time.Time
	ExpiresAt     sql.NullTime
}

type Wallet struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	BalanceBigint int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
