// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AcceptOrderCompletion(ctx context.Context, id uuid.UUID) error
	AddPermissionToRole(ctx context.Context, arg AddPermissionToRoleParams) error
	AddRoleToUser(ctx context.Context, arg AddRoleToUserParams) error
	AdminCountUsers(ctx context.Context, dollar_1 interface{}) (int64, error)
	AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]AdminListUsersRow, error)
	CheckOTPVerifyExist(ctx context.Context, verifyKey string) (bool, error)
	CheckRefreshToken(ctx context.Context, refreshToken string) (uuid.UUID, error)
	CheckRoomExist(ctx context.Context, arg CheckRoomExistParams) (Room, error)
	CheckUserExist(ctx context.Context, email string) (bool, error)
	// SẮP XẾP THEO THỜI GIAN CỦA TIN NHẮN CUỐI CÙNG
	CheckUserInRoom(ctx context.Context, arg CheckUserInRoomParams) (bool, error)
	CreateAnswer(ctx context.Context, arg CreateAnswerParams) (Answer, error)
	CreateDispute(ctx context.Context, arg CreateDisputeParams) (Dispute, error)
	CreateGig(ctx context.Context, arg CreateGigParams) (Gig, error)
	CreateGigPackage(ctx context.Context, arg CreateGigPackageParams) (GigPackage, error)
	CreateGigRequirement(ctx context.Context, arg CreateGigRequirementParams) (GigRequirement, error)
	// =========================
	// Ledger entries
	// =========================
	CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (CreateLedgerEntryRow, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	// =========================
	// Payment Transaction (provider callbacks)
	// =========================
	CreatePaymentTransaction(ctx context.Context, arg CreatePaymentTransactionParams) (CreatePaymentTransactionRow, error)
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	CreateRole(ctx context.Context, roleName string) (Role, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	// =========================
	// Topup / Payment intent
	// =========================
	CreateTopupOrder(ctx context.Context, arg CreateTopupOrderParams) (TopupOrder, error)
	CreateUserBase(ctx context.Context, arg CreateUserBaseParams) (uuid.UUID, error)
	CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (uuid.UUID, error)
	CreateWallet(ctx context.Context, arg CreateWalletParams) (CreateWalletRow, error)
	DeleteService(ctx context.Context, id uuid.UUID) error
	DeleteUserBase(ctx context.Context, userBaseID uuid.UUID) error
	GetAnswersByOrderID(ctx context.Context, id uuid.UUID) ([]Answer, error)
	GetCategories(ctx context.Context) ([]GetCategoriesRow, error)
	GetChatHistory(ctx context.Context, arg GetChatHistoryParams) ([]Message, error)
	GetDisputeByID(ctx context.Context, id uuid.UUID) (Dispute, error)
	GetDisputeByOrderID(ctx context.Context, orderID uuid.UUID) (Dispute, error)
	GetGigAndPackagesForOrder(ctx context.Context, id uuid.UUID) (GetGigAndPackagesForOrderRow, error)
	GetGigPackagesByGigID(ctx context.Context, gigID uuid.UUID) ([]GetGigPackagesByGigIDRow, error)
	GetGigRequirementsByGigID(ctx context.Context, gigID uuid.UUID) ([]GetGigRequirementsByGigIDRow, error)
	GetInfoOTP(ctx context.Context, verifyHashKey string) (GetInfoOTPRow, error)
	GetLastPendingTopupByOrder(ctx context.Context, orderID uuid.NullUUID) (TopupOrder, error)
	GetLedgerEntriesByWallet(ctx context.Context, walletID uuid.NullUUID) ([]GetLedgerEntriesByWalletRow, error)
	GetOrderByID(ctx context.Context, id uuid.UUID) (Order, error)
	GetOrderByIdempotency(ctx context.Context, idempotencyKey string) (Order, error)
	GetPaymentTransactionByProviderTx(ctx context.Context, arg GetPaymentTransactionByProviderTxParams) (GetPaymentTransactionByProviderTxRow, error)
	GetPermissionsByRoleID(ctx context.Context, roleID uuid.UUID) ([]Permission, error)
	GetPermissionsByUserID(ctx context.Context, userID uuid.UUID) ([]Permission, error)
	GetRoleIdByRoleName(ctx context.Context, roleName string) (uuid.UUID, error)
	GetRolesByUserID(ctx context.Context, userID uuid.UUID) ([]Role, error)
	GetRoomChatByUserId(ctx context.Context, user1ID uuid.UUID) ([]GetRoomChatByUserIdRow, error)
	GetRoomInfo(ctx context.Context, id uuid.UUID) (GetRoomInfoRow, error)
	GetService(ctx context.Context, id uuid.UUID) (GetServiceRow, error)
	GetTopupByIdempotencyKeyAndOrder(ctx context.Context, arg GetTopupByIdempotencyKeyAndOrderParams) (TopupOrder, error)
	GetTopupOrderByReference(ctx context.Context, referenceCode string) (TopupOrder, error)
	GetUserBaseToCheckLogin(ctx context.Context, email string) (GetUserBaseToCheckLoginRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserInfoToSetToken(ctx context.Context, userBaseID uuid.UUID) (GetUserInfoToSetTokenRow, error)
	GetWalletByUserID(ctx context.Context, userID uuid.UUID) (GetWalletByUserIDRow, error)
	GetWalletForUpdateByUser(ctx context.Context, userID uuid.UUID) (GetWalletForUpdateByUserRow, error)
	InsertOTPVerify(ctx context.Context, arg InsertOTPVerifyParams) (uuid.UUID, error)
	ListDisputes(ctx context.Context) ([]Dispute, error)
	ListOrdersByUser(ctx context.Context, buyerID uuid.UUID) ([]Order, error)
	ListUsersByType(ctx context.Context, roleName string) ([]Role, error)
	RemovePermissionFromRole(ctx context.Context, arg RemovePermissionFromRoleParams) error
	RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error
	SearchGigs(ctx context.Context, arg SearchGigsParams) ([]SearchGigsRow, error)
	SetChatHistory(ctx context.Context, arg SetChatHistoryParams) (Message, error)
	SubmitOrderDelivery(ctx context.Context, id uuid.UUID) error
	UpdateDisputeStatus(ctx context.Context, arg UpdateDisputeStatusParams) error
	UpdateLoginInfo(ctx context.Context, arg UpdateLoginInfoParams) error
	UpdateLogoutInfo(ctx context.Context, userBaseID uuid.UUID) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	UpdateService(ctx context.Context, arg UpdateServiceParams) (Gig, error)
	UpdateTopupOrderStatus(ctx context.Context, arg UpdateTopupOrderStatusParams) (UpdateTopupOrderStatusRow, error)
	UpdateTopupPaymentInfo(ctx context.Context, arg UpdateTopupPaymentInfoParams) (UpdateTopupPaymentInfoRow, error)
	UpdateUserBaseToken(ctx context.Context, arg UpdateUserBaseTokenParams) error
	UpdateUserVerificationStatus(ctx context.Context, verifyHashKey string) error
	UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) (UpdateWalletBalanceRow, error)
}

var _ Querier = (*Queries)(nil)
